/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description Newest-first; the first entry carries `is_current=True` - the same
         *     rule every other endpoint applies internally via `current_version_id`.
         */
        get: operations["list_versions_v1_projects__project_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layers */
        get: operations["list_layers_v1_projects__project_id__layers_get"];
        put?: never;
        /** Upload Layer */
        post: operations["upload_layer_v1_projects__project_id__layers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/layers/{layer_id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layer Attributes */
        get: operations["get_layer_attributes_v1_projects__project_id__layers__layer_id__attributes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Map Layer Attributes */
        patch: operations["map_layer_attributes_v1_projects__project_id__layers__layer_id__attributes_patch"];
        trace?: never;
    };
    "/v1/projects/{project_id}/layers/quadras/derive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Derive Quadras Layer
         * @description Dissolve Lote features sharing a `quadra_id` into a QUADRAS layer
         *     (ADR 009), toggleable/hideable like any other layer via the existing
         *     GET /layers and GET /layers/{id}/geojson routes - no new read endpoints
         *     needed. Replaces any previously derived QUADRAS layer for this version.
         */
        post: operations["derive_quadras_layer_v1_projects__project_id__layers_quadras_derive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/layers/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Layer
         * @description Hard delete (Frente 3, nota 52): remove a camada e suas feicoes.
         *     Feicoes de outras camadas que apontavam para estas (quadra/lote) sao
         *     desvinculadas, nunca removidas em cascata; resultados ja persistidos e
         *     documentos cartograficos ficam intactos - referencias orfas viram
         *     `integrity_warnings` na leitura (ADR 014, Decisao 8).
         */
        delete: operations["delete_layer_v1_projects__project_id__layers__layer_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/layers/{layer_id}/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer Geojson
         * @description `feature.id` is the persisted feature UUID - the join key for
         *     per-feature indicator values (`feature_key: feature_id` in the
         *     catalog, ADR 014).
         */
        get: operations["get_layer_geojson_v1_projects__project_id__layers__layer_id__geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Project */
        post: operations["analyze_project_v1_projects__project_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_v1_projects__project_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_projects__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_projects__project_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Related Features */
        post: operations["select_related_features_v1_projects__project_id__selection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Indicators */
        get: operations["list_indicators_v1_catalog_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/map-basemaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Basemaps */
        get: operations["list_basemaps_v1_map_basemaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{version_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Map Documents */
        get: operations["list_map_documents_v1_projects__project_id__versions__version_id__documents_get"];
        put?: never;
        /** Create Map Document */
        post: operations["create_map_document_v1_projects__project_id__versions__version_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Map Document */
        get: operations["get_map_document_v1_projects__project_id__documents__document_id__get"];
        /** Update Map Document */
        put: operations["update_map_document_v1_projects__project_id__documents__document_id__put"];
        post?: never;
        /** Delete Map Document */
        delete: operations["delete_map_document_v1_projects__project_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/documents/{document_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_v1_projects__project_id__documents__document_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/exports/{export_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver Export File */
        post: operations["deliver_export_file_v1_projects__project_id__exports__export_id__file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_v1_projects__project_id__exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRunOut */
        AnalysisRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            status: components["schemas"]["AnalysisStatus"];
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AnalysisStatus
         * @enum {string}
         */
        AnalysisStatus: "pending" | "running" | "completed" | "failed";
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Themes */
            themes: string[];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Analysis Run Id
             * Format: uuid
             */
            analysis_run_id: string;
            /** Status */
            status: string;
            /** Results */
            results: components["schemas"]["IndicatorResultOut"][];
        };
        /** AttributeMappingWarningOut */
        AttributeMappingWarningOut: {
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Message */
            message: string;
        };
        /**
         * BasemapColorMode
         * @enum {string}
         */
        BasemapColorMode: "none" | "light" | "dark";
        /** BasemapOut */
        BasemapOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Style Url */
            style_url: string | null;
            color_mode: components["schemas"]["BasemapColorMode"];
            /** Attribution */
            attribution: string | null;
            /** Export Allowed */
            export_allowed: boolean;
        };
        /** Body_deliver_export_file_v1_projects__project_id__exports__export_id__file_post */
        Body_deliver_export_file_v1_projects__project_id__exports__export_id__file_post: {
            /** File */
            file: string;
        };
        /** Body_upload_layer_v1_projects__project_id__layers_post */
        Body_upload_layer_v1_projects__project_id__layers_post: {
            layer_type: components["schemas"]["LayerType"];
            /** File */
            file: string;
            /** @default combined */
            import_profile: components["schemas"]["ImportProfile"];
            /** Attributes File */
            attributes_file?: string | null;
            /** Attributes Join Key */
            attributes_join_key?: string | null;
            /** Geometry Join Key */
            geometry_join_key?: string | null;
        };
        /** CatalogIndicatorOut */
        CatalogIndicatorOut: {
            /** Code */
            code: string;
            /** Theme */
            theme: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Unit */
            unit: string;
            /** Formula Version */
            formula_version: string;
            granularity: components["schemas"]["IndicatorGranularity"];
            feature_key: components["schemas"]["FeatureKey"] | null;
            value_shape: components["schemas"]["ValueShape"];
            /** Category Feature Property */
            category_feature_property: string | null;
            /** Required Layers */
            required_layers: string[];
            /** Optional Layers */
            optional_layers: string[];
        };
        /**
         * DetectedType
         * @enum {string}
         */
        DetectedType: "numeric" | "text" | "boolean" | "empty" | "mixed";
        /** DocumentLayer */
        DocumentLayer: {
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
            representation: components["schemas"]["Representation"];
            style: components["schemas"]["LayerStyle"];
            interaction?: components["schemas"]["Interaction"];
        };
        /** ErrorDetailOut */
        ErrorDetailOut: {
            /** Error */
            error: string;
            /** Message */
            message: string;
            /** Context */
            context: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelopeOut */
        ErrorEnvelopeOut: {
            detail: components["schemas"]["ErrorDetailOut"];
        };
        /** ExportCreateIn */
        ExportCreateIn: {
            /** Legend */
            legend: boolean;
            image: components["schemas"]["ExportImageSpecIn"];
            renderer: components["schemas"]["ExportRendererInfoIn"];
            /** Analysis Run Id */
            analysis_run_id?: string | null;
        };
        /** ExportImageSpecIn */
        ExportImageSpecIn: {
            ratio_id: components["schemas"]["ImageRatio"];
            resolution_id: components["schemas"]["ImageResolution"];
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Analysis Run Id */
            analysis_run_id: string | null;
            /** Format */
            format: string;
            status: components["schemas"]["ExportStatus"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** File Path */
            file_path: string | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** ExportRendererInfoIn */
        ExportRendererInfoIn: {
            /** Maplibre Version */
            maplibre_version: string;
            /** Frontend Version */
            frontend_version: string;
        };
        /**
         * ExportStatus
         * @description Mirrors AnalysisStatus's vocabulary (checkpoint 5.1, ADR 014 Decisao
         *     6) for consistency, even though no code path sets RUNNING in v1 - the
         *     backend never renders, it only freezes the snapshot (PENDING) and
         *     later archives the client-rendered artifact (COMPLETED/FAILED).
         * @enum {string}
         */
        ExportStatus: "pending" | "running" | "completed" | "failed";
        /**
         * FeatureKey
         * @description What keys a `por_feicao` dict value: feature UUIDs (joinable against
         *     `feature.id` in the layer GeoJSON) or `quadra_id` grouping strings
         *     (joinable against the derived quadras layer's `quadra_id` property).
         * @enum {string}
         */
        FeatureKey: "feature_id" | "quadra_id";
        /**
         * FeaturePanelConfig
         * @description ADR 014, Decisao 7 (nota 33) - core panel opened on feature click.
         *     Disabled by default: an absent/default config is a valid, inert
         *     document, not an error.
         */
        FeaturePanelConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Title Field */
            title_field?: string | null;
            /** @default compact */
            width: components["schemas"]["FeaturePanelWidth"];
            /** Blocks */
            blocks?: (components["schemas"]["TextBlock"] | components["schemas"]["TableBlock"])[];
        };
        /**
         * FeaturePanelFieldSource
         * @description Origin of a feature-panel field - deliberately its own enum (not
         *     RepresentationSource): a panel block never has a 'none' origin.
         * @enum {string}
         */
        FeaturePanelFieldSource: "property" | "indicator";
        /**
         * FeaturePanelWidth
         * @enum {string}
         */
        FeaturePanelWidth: "compact" | "medium";
        /** FieldFormat */
        FieldFormat: {
            type: components["schemas"]["FieldFormatType"];
            /** Decimals */
            decimals?: number | null;
            /** Prefix */
            prefix?: string | null;
            /** Suffix */
            suffix?: string | null;
        };
        /**
         * FieldFormatType
         * @enum {string}
         */
        FieldFormatType: "text" | "number";
        /**
         * FieldOrigin
         * @enum {string}
         */
        FieldOrigin: "source" | "mapped";
        /** FillStyle */
        FillStyle: {
            /** Color */
            color?: string | null;
            /** Palette */
            palette?: string[] | null;
            /** Opacity */
            opacity: number;
        };
        /** GeoJSONFeatureCollectionOut */
        GeoJSONFeatureCollectionOut: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Features */
            features: components["schemas"]["GeoJSONFeatureOut"][];
        };
        /** GeoJSONFeatureOut */
        GeoJSONFeatureOut: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageRatio
         * @enum {string}
         */
        ImageRatio: "screen" | "four_by_three" | "sixteen_by_nine";
        /**
         * ImageResolution
         * @enum {string}
         */
        ImageResolution: "1x" | "2x";
        /**
         * ImportProfile
         * @description Whether a layer's attributes arrived embedded in the geometry file
         *     (``combined``, the historical/default behaviour) or as a separate CSV
         *     joined by key (``split`` - nota 53/54).
         * @enum {string}
         */
        ImportProfile: "combined" | "split";
        /**
         * IndicatorGranularity
         * @description Spatial granularity of the indicator's persisted value.
         * @enum {string}
         */
        IndicatorGranularity: "projeto" | "por_feicao";
        /** IndicatorResultOut */
        IndicatorResultOut: {
            /** Indicator Code */
            indicator_code: string;
            /** Theme */
            theme: string;
            /** Formula Version */
            formula_version: string;
            /** Value */
            value: number | string | {
                [key: string]: unknown;
            } | null;
            /** Unit */
            unit: string;
            /** Metric Crs */
            metric_crs: string | null;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Source Layers */
            source_layers: string[];
            /** Contributing Feature Ids */
            contributing_feature_ids: string[];
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /** IntegrityWarningOut */
        IntegrityWarningOut: {
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Interaction */
        Interaction: {
            /** Tooltip Fields */
            tooltip_fields?: string[];
            /**
             * Selectable
             * @default true
             */
            selectable: boolean;
            feature_panel?: components["schemas"]["FeaturePanelConfig"];
            /** Filters */
            filters?: null;
        };
        /** LayerAttributeMappingIn */
        LayerAttributeMappingIn: {
            /** Mappings */
            mappings: {
                [key: string]: string | null;
            };
        };
        /** LayerAttributeMappingOut */
        LayerAttributeMappingOut: {
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Status */
            status: string;
            /** Features Updated */
            features_updated: number;
            /** Warnings */
            warnings: components["schemas"]["AttributeMappingWarningOut"][];
        };
        /** LayerAttributesOut */
        LayerAttributesOut: {
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Source Fields */
            source_fields: string[];
            /** Sample Values */
            sample_values: {
                [key: string]: string[];
            };
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string | null;
            };
            /** Feature Count */
            feature_count: number;
            /** Fields */
            fields: components["schemas"]["RepresentationFieldOut"][];
            /** Compatible Indicators */
            compatible_indicators: string[];
        };
        /** LayerOut */
        LayerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            layer_type: components["schemas"]["LayerType"];
            /** Source Filename */
            source_filename: string | null;
            /** Geometry Type */
            geometry_type: string | null;
            /** Feature Count */
            feature_count: number;
            status: components["schemas"]["LayerStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            import_profile: components["schemas"]["ImportProfile"];
            /** Attributes Filename */
            attributes_filename: string | null;
            /** Attributes Join Key */
            attributes_join_key: string | null;
            /** Geometry Join Key */
            geometry_join_key: string | null;
            /** Join Summary */
            join_summary: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * LayerStatus
         * @enum {string}
         */
        LayerStatus: "uploaded" | "mapped" | "validated" | "error";
        /** LayerStyle */
        LayerStyle: {
            fill: components["schemas"]["FillStyle"];
            stroke: components["schemas"]["StrokeStyle"];
            /** Null Color */
            null_color?: string | null;
            /** Labels */
            labels?: null;
        };
        /**
         * LayerType
         * @enum {string}
         */
        LayerType: "perimetro" | "quadras" | "lotes" | "sistema_viario" | "uso_solo" | "areas_verdes" | "equipamentos" | "edificacoes" | "desconexoes_viarias" | "territorio";
        /**
         * MapDocumentConfig
         * @description The JSONB payload of a map document (ADR 014, Decisao 2).
         */
        MapDocumentConfig: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1";
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Basemap Id */
            basemap_id: string;
            viewport: components["schemas"]["Viewport"];
            /** Layers */
            layers?: components["schemas"]["DocumentLayer"][];
        };
        /** MapDocumentCreateIn */
        MapDocumentCreateIn: {
            /** Name */
            name: string;
            config: components["schemas"]["MapDocumentConfig"];
        };
        /** MapDocumentOut */
        MapDocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Name */
            name: string;
            config: components["schemas"]["MapDocumentConfig"];
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MapDocumentUpdateIn */
        MapDocumentUpdateIn: {
            /** Name */
            name: string;
            config: components["schemas"]["MapDocumentConfig"];
            /** Expected Revision */
            expected_revision: number;
        };
        /**
         * MapDocumentWithWarningsOut
         * @description Only the single-item GET carries this (ADR 014, Decisao 8) - the
         *     list route stays cheap, without a diagnostic pass per document.
         */
        MapDocumentWithWarningsOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Name */
            name: string;
            config: components["schemas"]["MapDocumentConfig"];
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Integrity Warnings */
            integrity_warnings: components["schemas"]["IntegrityWarningOut"][];
        };
        /**
         * NullBehavior
         * @enum {string}
         */
        NullBehavior: "transparent" | "color";
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Municipality */
            municipality?: string | null;
            /** State */
            state?: string | null;
            /** Typology */
            typology?: string | null;
            /** Approx Area M2 */
            approx_area_m2?: number | null;
            /** Description */
            description?: string | null;
            /** Team */
            team?: string | null;
            /** Crs Hint */
            crs_hint?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Municipality */
            municipality: string | null;
            /** State */
            state: string | null;
            /** Typology */
            typology: string | null;
            /** Approx Area M2 */
            approx_area_m2: number | null;
            /** Description */
            description: string | null;
            /** Team */
            team: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectVersionOut */
        ProjectVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Name */
            name: string;
            /** Number */
            number: number;
            /** Description */
            description: string | null;
            /** Parent Version Id */
            parent_version_id: string | null;
            status: components["schemas"]["ProjectVersionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Current */
            is_current: boolean;
        };
        /**
         * ProjectVersionStatus
         * @enum {string}
         */
        ProjectVersionStatus: "active" | "concluded" | "archived";
        /** QuadrasDeriveOut */
        QuadrasDeriveOut: {
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Quadra Count */
            quadra_count: number;
            /** Lot Count */
            lot_count: number;
        };
        /** Representation */
        Representation: {
            source: components["schemas"]["RepresentationSource"];
            /** Field */
            field?: string | null;
            /** Indicator Code */
            indicator_code?: string | null;
            mode: components["schemas"]["RepresentationMode"];
            scale?: components["schemas"]["ScaleType"] | null;
            /** Classes */
            classes?: number | null;
            /** Stops */
            stops?: number[] | null;
            /** @default transparent */
            null_behavior: components["schemas"]["NullBehavior"];
        };
        /**
         * RepresentationFieldOut
         * @description Aggregated stats + cartographic recommendation for one field
         *     (DOC-BE-004 / ADR 014). The recommendation is a suggestion; the
         *     authoritative validation happens on the map document itself.
         */
        RepresentationFieldOut: {
            /** Field */
            field: string;
            origin: components["schemas"]["FieldOrigin"];
            detected_type: components["schemas"]["DetectedType"];
            /** Present Count */
            present_count: number;
            /** Empty Count */
            empty_count: number;
            /** Cardinality */
            cardinality: number;
            /** Distinct Values */
            distinct_values: string[] | null;
            /** Min Value */
            min_value: number | null;
            /** Max Value */
            max_value: number | null;
            recommended_mode: components["schemas"]["RepresentationMode"] | null;
            /** Unsuitable Reason */
            unsuitable_reason: string | null;
        };
        /**
         * RepresentationMode
         * @enum {string}
         */
        RepresentationMode: "single" | "categorical" | "sequential" | "diverging";
        /**
         * RepresentationSource
         * @enum {string}
         */
        RepresentationSource: "property" | "indicator" | "none";
        /**
         * ScaleType
         * @description Vocabulary shared with kepler.gl/d3-scale (ADR 014, nota 32).
         * @enum {string}
         */
        ScaleType: "ordinal" | "quantile" | "quantize" | "linear" | "sqrt" | "log" | "threshold";
        /** SelectionRequest */
        SelectionRequest: {
            /** Target Layer Type */
            target_layer_type: string;
            relation?: components["schemas"]["SpatialRelation"] | null;
            /** Source Feature Ids */
            source_feature_ids?: string[] | null;
            /** Distance M */
            distance_m?: number | null;
            /** Attribute Filters */
            attribute_filters?: {
                [key: string]: string;
            } | null;
        };
        /** SelectionResponse */
        SelectionResponse: {
            /** Feature Ids */
            feature_ids: string[];
            /** Count */
            count: number;
        };
        /**
         * SpatialRelation
         * @description Vocabulary shared by the interactive selection endpoint (ADR 007) and,
         *     later, the batch lot-block association logic in Epico 8.
         * @enum {string}
         */
        SpatialRelation: "intersects" | "contains" | "within" | "dwithin";
        /**
         * StrokeLineStyle
         * @enum {string}
         */
        StrokeLineStyle: "solid" | "dashed" | "dotted";
        /** StrokeStyle */
        StrokeStyle: {
            /** Color */
            color: string;
            /** Width Px */
            width_px: number;
            /** @default solid */
            style: components["schemas"]["StrokeLineStyle"];
            /** Opacity */
            opacity: number;
        };
        /** TableBlock */
        TableBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /**
             * Layout
             * @default key_value
             * @constant
             */
            layout: "key_value";
            /** Fields */
            fields: components["schemas"]["TableField"][];
        };
        /** TableField */
        TableField: {
            source: components["schemas"]["FeaturePanelFieldSource"];
            /** Key */
            key: string;
            /** Label */
            label: string;
            format?: components["schemas"]["FieldFormat"] | null;
        };
        /** TextBlock */
        TextBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            source: components["schemas"]["FeaturePanelFieldSource"];
            /** Field */
            field: string;
            /** @default body */
            style: components["schemas"]["TextBlockStyle"];
        };
        /**
         * TextBlockStyle
         * @enum {string}
         */
        TextBlockStyle: "body" | "subtitle";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueShape
         * @description Structure of the raw value this indicator persists (`value`/
         *     `value_json` in `indicator_results`) - drives which visualization the
         *     frontend picks for it (indicator representation review, 2026-07-20).
         *     Independent of `unit`/number formatting, which stays on the
         *     calculation result (`IndicatorDefinition.unit`), not here.
         *
         *     - SCALAR: one number for the whole project.
         *     - CATEGORY_BREAKDOWN: dict[categoria -> numero] for the whole project
         *       (e.g. area/percentual por macroarea ou uso do solo).
         *     - CATEGORICAL_LABEL: a single category name for the whole project (or
         *       null on a tie/no data) - not a number at all.
         *     - FEATURE_SERIES: one number per feature/quadra (`por_feicao`) - the
         *       existing min/mean/max + ranked-list view already suits this.
         *     - FEATURE_COMPOUND: one compound record (dict of sub-fields) per
         *       feature/quadra (`por_feicao`) - needs a table, not a single bar.
         * @enum {string}
         */
        ValueShape: "scalar" | "category_breakdown" | "categorical_label" | "feature_series" | "feature_compound";
        /** Viewport */
        Viewport: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            /** Zoom */
            zoom: number;
            /**
             * Bearing
             * @default 0
             */
            bearing: number;
            /**
             * Pitch
             * @default 0
             */
            pitch: number;
        };
        /** WarningOut */
        WarningOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Feature Ids */
            feature_ids: string[];
            /** Severity */
            severity: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_v1_projects__project_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectVersionOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_layers_v1_projects__project_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_layer_v1_projects__project_id__layers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_layer_v1_projects__project_id__layers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_attributes_v1_projects__project_id__layers__layer_id__attributes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerAttributesOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_layer_attributes_v1_projects__project_id__layers__layer_id__attributes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerAttributeMappingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerAttributeMappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derive_quadras_layer_v1_projects__project_id__layers_quadras_derive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuadrasDeriveOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    delete_layer_v1_projects__project_id__layers__layer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_geojson_v1_projects__project_id__layers__layer_id__geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_project_v1_projects__project_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    get_results_v1_projects__project_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResultOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_projects__project_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_projects__project_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_related_features_v1_projects__project_id__selection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    list_indicators_v1_catalog_indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogIndicatorOut"][];
                };
            };
        };
    };
    list_basemaps_v1_map_basemaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasemapOut"][];
                };
            };
        };
    };
    list_map_documents_v1_projects__project_id__versions__version_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDocumentOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_map_document_v1_projects__project_id__versions__version_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapDocumentCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDocumentOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    get_map_document_v1_projects__project_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDocumentWithWarningsOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_map_document_v1_projects__project_id__documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapDocumentUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDocumentOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    delete_map_document_v1_projects__project_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_v1_projects__project_id__documents__document_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    deliver_export_file_v1_projects__project_id__exports__export_id__file_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                export_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_deliver_export_file_v1_projects__project_id__exports__export_id__file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
        };
    };
    get_export_v1_projects__project_id__exports__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
